version: '2.1'
networks: {}
volumes: 
    resin-data: {}
services:
  icecast:
    image: jstnn/arm-icecast
    ports:
      - "8000:8000"
      - "80:80"
    network_mode: host
    privileged: true
    restart: always

  # Add your host volumen in path/to/... or add your own volume below
  mpd:
    image: jstnn/arm-mpd
    ports:
      - "6600:6600"
    depends_on:
      - icecast
    # volumes:
    #   - resin-data:/var/lib/mpd/music
    #   - resin-data:/var/lib/mpd/playlists
    #   - resin-data:/var/lib/mpd/database
    network_mode: host
    privileged: true
    restart: always

  sima:
    image: jstnn/arm-sima
    depends_on:
      - mpd
    network_mode: host
    privileged: true
    restart: always

  ympd:
    image: jstnn/arm-ympd
    ports:
      - "8080:8080"
    depends_on:
      - mpd
    network_mode: host
    privileged: true
    restart: always
  
  # pureftpd:
  #   build: ./pureftpd
  #   ports:
  #     - "21:21"
  #     - "30000-30009:30000-30009"
  #   volumes:
  #     - /data/radio/music:/home/ftpuser/sativo
  #   environment:
  #     PUBLICHOST: localhost
  #   privileged: true

# If you use your own volumes instead host volumes, uncomment this section
# volumes:
#   mpd_music:
#     external: true
#   mpd_playlists:
#     external: true
#   mpd_database:
#     external: true


