version: '2'
networks:
  music_stack:
    driver: bridge
volumes:
  music:
  playlists:
  database:
services:
  icecast:
    build: ./icecast
    ports:
      - "8000:8000"
      - "80:80"
    networks:
      - music_stack
    restart: always
    privileged: true    

  mpd:   
    build: ./mpd
    ports:
      - "6600:6600"
    depends_on:
      - icecast
    volumes:
      - music:/var/lib/mpd/music
      - playlists:/var/lib/mpd/playlists
      - database:/var/lib/mpd/database
    networks:
      - music_stack
    restart: always
    privileged: true    

  sima:
    build: ./sima
    depends_on:
      - mpd
    networks:
      - music_stack
    restart: always
    privileged: true    

  ympd:
    build: ./ympd
    expose:
      - "8080"
    ports:
      - "8080:8080"
    depends_on:
      - mpd
    networks:
      - music_stack
    restart: always
    privileged: true    
  
  # pureftpd:
  #   build: ./pureftpd
  #   ports:
  #     - "21:21"
  #     - "30000-30009:30000-30009"
  #   volumes:
  #     - /data/radio/music:/home/ftpuser/sativo
  #   environment:
  #     PUBLIChost: localhost
  #   privileged: true

# If you use your own volumes instead host volumes, uncomment this section
# volumes:
#   mpd_music:
#     external: true
#   mpd_playlists:
#     external: true
#   mpd_database:
#     external: true


