version: '2'
volumes:
  resin-data:
services:
  icecast:
    build: ./icecast
    expose:
      - "8000"
    restart: always
    privileged: true    

  mpd:   
    build: ./mpd
    depends_on:
      - icecast
    volumes:
      - resin-data:/var/lib/mpd/music
    restart: always
    privileged: true    

  sima:
    build: ./sima
    depends_on:
      - mpd
    restart: always
    privileged: true    

  ympd:
    build: ./ympd
    expose:
      - "8080"
    depends_on:
      - mpd
    restart: always
    privileged: true    
  
  proxy:
    build: ./haproxy
    depends_on:
      - ympd
    ports:
      - "80:80"
    restart: always
    privileged: true

  # pureftpd:
  #   build: ./pureftpd
  #   ports:
  #     - "21:21"
  #     - "30000-30009:30000-30009"
  #   volumes:
  #     - /data/radio/music:/home/ftpuser/sativo
  #   environment:
  #     PUBLIC"host": local"host"
  #   privileged: true

# If you use your own volumes instead "host" volumes, uncomment this section
# volumes:
#   mpd_music:
#     external: true
#   mpd_playlists:
#     external: true
#   mpd_database:
#     external: true


