version: '2'

volumes: 
    resin-data:

services:
  icecast:
    image: jstnn/arm-icecast
    privileged: true
    restart: always
    expose:
      - "8000"
      - "80"

  # Add your host volumen in path/to/... or add your own volume below
  mpd:
    image: jstnn/arm-mpd
    privileged: true
    restart: always
    expose:
      - "6600"
    depends_on:
      - icecast
    volumes:
      - resin-data/radio/music:/var/lib/mpd/music
      - resin-data/radio/playlists:/var/lib/mpd/playlists
      - resin-data/radio/database:/var/lib/mpd/database

  sima:
    image: jstnn/arm-sima
    depends_on:
      - mpd

  ympd:
    image: jstnn/arm-ympd
    privileged: true
    restart: always
    expose:
      - "8080"
    depends_on:
      - mpd
  
  # pureftpd:
  #   build: ./pureftpd
  #   ports:
  #     - "21:21"
  #     - "30000-30009:30000-30009"
  #   volumes:
  #     - /data/radio/music:/home/ftpuser/sativo
  #   environment:
  #     PUBLICHOST: localhost
  #   privileged: true

# network_mode:
#   radio:
#    er: "hostd"

# If you use your own volumes instead host volumes, uncomment this section
# volumes:
#   mpd_music:
#     external: true
#   mpd_playlists:
#     external: true
#   mpd_database:
#     external: true


