version: '2'
networks: {}
volumes:
  music:
  playlists:
  database:
services:
  icecast:
    image: jstnn/arm-icecast
    expose:
      - "8000"
      - "80"
    ports:
      - "8000:8000"
      - "80:80"
    network_mode: bridge
    restart: always

  mpd:
    image: jstnn/arm-mpd
    # build: ./mpd
    expose:
      - "6600"
    ports:
      - "6600:6600"
    depends_on:
      - icecast
    volumes:
      - music:/var/lib/mpd/music
      - playlists:/var/lib/mpd/playlists
      - database:/var/lib/mpd/database
    network_mode: bridge
    restart: always

  sima:
    image: jstnn/arm-sima
    depends_on:
      - mpd
    network_mode: bridge
    restart: always

  ympd:
    image: jstnn/arm-ympd
    expose:
      - "8080"
    ports:
      - "8080:8080"
    depends_on:
      - mpd
    network_mode: bridge
    restart: always
  
  # pureftpd:
  #   build: ./pureftpd
  #   ports:
  #     - "21:21"
  #     - "30000-30009:30000-30009"
  #   volumes:
  #     - /data/radio/music:/home/ftpuser/sativo
  #   environment:
  #     PUBLICbridge: localbridge
  #   privileged: true

# If you use your own volumes instead bridge volumes, uncomment this section
# volumes:
#   mpd_music:
#     external: true
#   mpd_playlists:
#     external: true
#   mpd_database:
#     external: true


