version: '2'
volumes:
  music:
  playlists:
  database:
services:
  icecast:
    build: ./icecast
    expose:
      - "8000"
    restart: always
    privileged: true    

  mpd:   
    build: ./mpd
    depends_on:
      - icecast
    volumes:
      - music:/var/lib/mpd/music
      - playlists:/var/lib/mpd/playlists
      - database:/var/lib/mpd/database
    restart: always
    privileged: true    

  sima:
    build: ./sima
    depends_on:
      - mpd
    restart: always
    privileged: true    

  ympd:
    build: ./ympd
    expose:
      - "8080"
    depends_on:
      - mpd
    restart: always
    privileged: true    
  
  proxy:
    build: ./haproxy
    depends_on:
      - icecast
      - mpd
    ports:
      - "80:8080"
  # pureftpd:
  #   build: ./pureftpd
  #   ports:
  #     - "21:21"
  #     - "30000-30009:30000-30009"
  #   volumes:
  #     - /data/radio/music:/home/ftpuser/sativo
  #   environment:
  #     PUBLIC"host": local"host"
  #   privileged: true

# If you use your own volumes instead "host" volumes, uncomment this section
# volumes:
#   mpd_music:
#     external: true
#   mpd_playlists:
#     external: true
#   mpd_database:
#     external: true


