version: '2'

services:
  icecast:
    image: jstnn/arm-icecast
    ports:
      - "8000:8000"
      - "80:80"
    network_mode:
      - "bridge"

  # Add your host volumen in path/to/... or add your own volume below
  mpd:
    image: jstnn/arm-mpd
    ports:
      - "6600:6600"
    depends_on:
      - icecast
    network_mode:
      - "bridge"
    volumes:
      - /data/radio/music:/var/lib/mpd/music
      - /data/radio/playlists:/var/lib/mpd/playlists
      - /data/radio/database:/var/lib/mpd/database

  sima:
    image: jstnn/arm-sima
    depends_on:
      - mpd
    network_mode:
      - "bridge"

  ympd:
    image: jstnn/arm-ympd
    ports:
      - "8080:8080"
    depends_on:
      - mpd
    network_mode:
      - "bridge"
  
  # pureftpd:
  #   build: ./pureftpd
  #   ports:
  #     - "21:21"
  #     - "30000-30009:30000-30009"
  #   volumes:
  #     - /data/radio/music:/home/ftpuser/sativo
  #   environment:
  #     PUBLICHOST: localhost
  #   privileged: true

# network_mode:
#   radio:
#     driver: ""bridge"d"

# If you use your own volumes instead host volumes, uncomment this section
# volumes:
#   mpd_music:
#     external: true
#   mpd_playlists:
#     external: true
#   mpd_database:
#     external: true


